[package]
name = "shell_parser"
version = "0.1.0"
authors = ["Wez Furlong"]
edition = "2018"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
lazy_static = "1.3"
shell_lexer = { path = "../shell_lexer" }

[dev-dependencies]
pretty_assertions = "0.6"
